# Generated by Django 3.1.7 on 2021-04-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=256)),
                ('template', models.TextField()),
                ('players', models.IntegerField()),
                ('difficulty', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=128, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('job', models.CharField(choices=[('be', 'Back-End Engineer'), ('fe', 'Front-End Engineer'), ('fs', 'Full Stack Engineer'), ('ot', 'Other'), ('qa', 'QA Engineer'), ('se', 'System Engineer')], default='System Engineer', max_length=60)),
                ('elo', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissions', models.ManyToManyField(related_name='tournaments', to='SSD_API.Submission')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='SSD_API.user'),
        ),
        migrations.AddField(
            model_name='submission',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='SSD_API.game'),
        ),
    ]
