# Generated by Django 3.1.7 on 2021-03-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SSD_API', '0002_auto_20210322_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(choices=[('be', 'Back-End Engineer'), ('fe', 'Front-End Engineer'), ('fs', 'Full Stack Engineer'), ('ot', 'Other'), ('qa', 'QA Engineer'), ('se', 'System Engineer')], default='System Engineer', max_length=60),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='SSD_API.user')),
            ],
        ),
    ]
